Add controllers (Sprint 1)
EvgenyGH/java-shareit pull request #1
Opened 2022-07-23 21:04 UTC by EvgenyGH

2022-07-24 21:15 UTC, kukolev requested changes

2022-07-24 21:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +    private void validateItem(@Valid Item item) {
Метод не реализован, нужно реализовать или удалить. Валидацию нужно перенести в сервис, т.к. валидация это часть бизнес-логики.

2022-07-24 21:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        if (items.containsKey(userId)) {
Здесь реализована бизнес-логика. Хранилище должно только работать над сохранением данных в памяти. Бизнес-логику нужно реализовать в сервисе.

Аналогично нужно поправить во всех методах класса.

2022-07-24 21:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDao.java
> +        if (emails.contains(user.getEmail())) {
Здесь реализована бизнес-логика. Хранилище должно только работать над сохранением данных в памяти. Бизнес-логику нужно реализовать в сервисе.

Аналогично нужно поправить во всех методах класса.

2022-07-25 20:33 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +    private void validateItem(@Valid Item item) {
Исправлено.

2022-07-25 20:33 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        if (items.containsKey(userId)) {
Исправлено.

2022-07-25 20:33 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/user/dao/InMemoryUserDao.java
> +        if (emails.contains(user.getEmail())) {
Исправлено.

2022-07-26 07:22 UTC, kukolev requested changes

2022-07-26 07:22 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        return itemFound; //itemFound;
Этот комментарий никак не помогает анализировать код. Бесполезные комментарии нужно удалять, чтобы не мешали.

2022-07-26 14:47 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        return itemFound; //itemFound;
Комментарий удален.

2022-07-26 16:48 UTC, kukolev approved these changes

2022-07-26 17:01 UTC, merged