Add bookings
EvgenyGH/java-shareit pull request #2
Opened 2022-08-07 11:41 UTC by EvgenyGH

2022-08-08 07:36 UTC, kukolev requested changes

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return id != null ? id.hashCode() : 0;
Хэшкод интеджера это и есть его значение. Этот код можно упростить, если возвращать id, а не id.hashCode()

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idOrderByStartDateDesc(Long bookerId);
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

Аналогично нужно поправить ниже.

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idAndStatusOrderByStartDateDesc(Long bookerId, Status status);
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

Аналогично нужно поправить ниже.

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idAndStartDateIsBeforeAndEndDateIsAfterSorted(long userId, LocalDateTime dateTime);
Метод можно назвать проще, т.к. есть аннотация `@Query`

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/Item.java
> +        return id != null ? id.hashCode() : 0;
Хэшкод интеджера это и есть его значение. Этот код можно упростить, если возвращать id, а не id.hashCode()

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Optional<Item> itemOpt = itemRepository.findById(itemId);
Здесь лучше дописать в конце .orElseThrow() и добавить там выброс исключения. Тогда не нужно будет писать условие как сделано ниже.

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> userItems = itemRepository.findAllByOwnerOrderById(user);
Здесь лучше дописать в конце .orElseThrow() и добавить там выброс исключения. Тогда не нужно будет писать условие как сделано ниже.

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Optional<Booking> bookingOpt = bookingRepository
Здесь лучше дописать в конце .orElseThrow() и добавить там выброс исключения. Тогда не нужно будет писать условие как сделано ниже.

2022-08-08 07:36 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/comment/dto/CommentDto.java
> +    // author — автор комментария
Лишний пробел перед словом author. Нужно поправить, чтобы комментарии были в одном стиле.

2022-08-08 17:10 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +        return id != null ? id.hashCode() : 0;
id типа long, поэтому просто вернуть id не получится, т.к. hashCode() должен возвращает int.

2022-08-08 17:10 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/Item.java
> +        return id != null ? id.hashCode() : 0;
id типа long, поэтому просто вернуть id не получится, т.к. hashCode() должен возвращает int.

2022-08-08 17:10 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/comment/dto/CommentDto.java
> +    // author — автор комментария
Исправлено

2022-08-08 18:03 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idOrderByStartDateDesc(Long bookerId);
Исправлено

2022-08-08 18:03 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idAndStatusOrderByStartDateDesc(Long bookerId, Status status);
Исправлено

2022-08-08 18:03 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBooker_idAndStartDateIsBeforeAndEndDateIsAfterSorted(long userId, LocalDateTime dateTime);
Исправлено

2022-08-08 18:45 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Optional<Item> itemOpt = itemRepository.findById(itemId);
Исключения в проекте являются наследниками RuntimeExeption и не проверяются. При этом orElseThrow ожидает наследников Throwable. В данном случае нужно будет или дополнить определение метода throws Throwable, что заставит передавать это исключение во всех методах до самого верха и и в тоже время будет дезинформировать будущих разработчиков, которые будут работать с этим кодом, о необходимости обработать исключение. Или это исключение нужно будет поймать на месте, что, на мой взгляд, тоже хуже кейса if.

2022-08-08 18:45 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        List<Item> userItems = itemRepository.findAllByOwnerOrderById(user);
Исключения в проекте являются наследниками RuntimeExeption и не проверяются. При этом orElseThrow ожидает наследников Throwable. В данном случае нужно будет или дополнить определение метода throws Throwable, что заставит передавать это исключение во всех методах до самого верха и и в тоже время будет дезинформировать будущих разработчиков, которые будут работать с этим кодом, о необходимости обработать исключение. Или это исключение нужно будет поймать на месте, что, на мой взгляд, тоже хуже кейса if.

2022-08-08 18:45 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        Optional<Booking> bookingOpt = bookingRepository
Исключения в проекте являются наследниками RuntimeExeption и не проверяются. При этом orElseThrow ожидает наследников Throwable. В данном случае нужно будет или дополнить определение метода throws Throwable, что заставит передавать это исключение во всех методах до самого верха и и в тоже время будет дезинформировать будущих разработчиков, которые будут работать с этим кодом, о необходимости обработать исключение. Или это исключение нужно будет поймать на месте, что, на мой взгляд, тоже хуже кейса if.

2022-08-09 16:44 UTC, kukolev requested changes

2022-08-09 16:44 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        //Optional<Item> itemOpt = itemRepository.findById(itemId);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-09 16:44 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-09 18:34 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        //Optional<Item> itemOpt = itemRepository.findById(itemId);
удалено

2022-08-09 18:35 UTC, EvgenyGH commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
удалено

2022-08-10 07:26 UTC, kukolev approved these changes

2022-08-10 16:08 UTC, merged