Add item requests
EvgenyGH/java-shareit pull request #3
Opened 2022-08-21 15:06 UTC by EvgenyGH

Sprint 15

2022-08-22 06:28 UTC, kukolev requested changes

2022-08-22 06:28 UTC, kukolev commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +        //@SQL()
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-22 06:28 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void bookingExceptionHandlerTest() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-22 06:28 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/CommentRepositoryTest.java
> +    //todo
Это TODO нужно удалить, т.к. функционал реализован. Либо нужно написать что осталось реализовать.

2022-08-22 06:28 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void itemExceptionHandlerTest() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-22 15:24 UTC, EvgenyGH commented on src/test/java/ru/practicum/shareit/ShareItTests.java
> +        //@SQL()
Спасибо! Удален.

2022-08-22 15:25 UTC, EvgenyGH commented on src/test/java/ru/practicum/shareit/item/CommentRepositoryTest.java
> +    //todo
Спасибо! Удалено.

2022-08-22 15:35 UTC, EvgenyGH commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void bookingExceptionHandlerTest() throws Exception {
Спасибо! Исправлено.

2022-08-22 15:39 UTC, EvgenyGH commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    void itemExceptionHandlerTest() throws Exception {
Спасибо! Исправлено.

2022-08-23 06:31 UTC, kukolev requested changes

2022-08-23 06:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .getBookingByBookerStatusPastOrdered(userId, LocalDateTime.now(), PageRequest.of(from / size, size));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-23 06:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -                        , LocalDateTime.now());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-23 06:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookings = bookingRepository.getBookingByOwnerStatusAllOrdered(userId, PageRequest.of(from / size, size));
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-23 06:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    //Информация по датам аренды только для пользователя, который еще не арендовал вещ.
Орфографическая ошибка в слове «вещь». Нужно исправить.

2022-08-23 06:31 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      //Информация по датам аренды только для пользователя, который еще не арендовал вещ.
Орфографическая ошибка в слове «вещь». Нужно исправить.

2022-08-23 14:46 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .getBookingByBookerStatusPastOrdered(userId, LocalDateTime.now(), PageRequest.of(from / size, size));
Спасибо! Исправлено.

2022-08-23 14:46 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> -                        , LocalDateTime.now());
Спасибо! Исправлено.

2022-08-23 14:47 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                bookings = bookingRepository.getBookingByOwnerStatusAllOrdered(userId, PageRequest.of(from / size, size));
Спасибо! Исправлено.

2022-08-23 14:47 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    //Информация по датам аренды только для пользователя, который еще не арендовал вещ.
Спасибо! Исправлено.

2022-08-23 14:47 UTC, EvgenyGH commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      //Информация по датам аренды только для пользователя, который еще не арендовал вещ.
Спасибо! Исправлено.

2022-08-23 16:14 UTC, kukolev approved these changes

2022-08-23 18:30 UTC, merged