Sprint 16
EvgenyGH/java-shareit pull request #7
Opened 2022-09-05 15:09 UTC by EvgenyGH

2022-09-06 06:21 UTC, kukolev requested changes
Общие замечания:

1. Не выполнено требование ТЗ: Вынести в shareIt-gateway всю логику валидации входных данных — кроме той, которая требует работы с БД. Необходимо вынести валидацию входных данных в shareIt-gateway.

2. Эти файлы не относятся к исходному коду проекта. Все лишние файлы нужно удалить из пул-реквеста:  

- server/target/shareit-server-0.0.1-SNAPSHOT-exec.jar
- server/target/shareit-server-0.0.1-SNAPSHOT-exec.jar

2022-09-06 06:21 UTC, kukolev commented on gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +    // Затем статус бронирования становится либо APPROVED, либо REJECTED
Лишний пробел после // смотрится не аккуратно. По моему лучше удалить пробел для единообразия.

2022-09-06 06:58 UTC, EvgenyGH commented on gateway/src/main/java/ru/practicum/shareitgateway/booking/BookingController.java
> +    // Затем статус бронирования становится либо APPROVED, либо REJECTED
Удалено.

2022-09-07 05:40 UTC, kukolev approved these changes

2022-09-07 10:58 UTC, merged